### ISSUE TITLE
Panic when given a secret with a metadata.uid

### ISSUE THREAD

**Issue by benmoss** [k14s/kapp#158]
```
$ kapp version
kapp version 0.34.0
```

```
$ cat <<EOF | kapp deploy -a foo -f -
apiVersion: v1
kind: Secret
metadata:
  name: foo
  uid: foo
EOF
```

```
Target cluster 'https://127.0.0.1:40749' (nodes: kind-control-plane)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xfd4f16]

goroutine 1 [running]:
github.com/k14s/kapp/pkg/kapp/resources.APIVersionKindMatcher.Matches(0xc000855ae8, 0x19, 0x1376560, 0x3, 0x0, 0x0, 0x8)
        github.com/k14s/kapp@/pkg/kapp/resources/matchers.go:29 +0x26
github.com/k14s/kapp/pkg/kapp/resourcesmisc.NewKappctrlK14sIoV1alpha1App(0x0, 0x0, 0xc00038da40)
        github.com/k14s/kapp@/pkg/kapp/resourcesmisc/kappctrl_k14s_io_v1alpha1_app.go:28 +0x94
github.com/k14s/kapp/pkg/kapp/clusterapply.ConvergedResourceFactory.New.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0xc000855dc8, 0xc000855db0, 0x15a16a0, 0xc000c6a780, 0x15c3460)
        github.com/k14s/kapp@/pkg/kapp/clusterapply/converged_resource_factory.go:33 +0x35
github.com/k14s/kapp/pkg/kapp/clusterapply.ConvergedResource.isResourceDoneApplying(0x0, 0x0, 0x0, 0xc00022c230, 0xd, 0xd, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/k14s/kapp@/pkg/kapp/clusterapply/converged_resource.go:156 +0xbb
github.com/k14s/kapp/pkg/kapp/clusterapply.ConvergedResource.IsDoneApplying(0x0, 0x0, 0x0, 0xc00022c230, 0xd, 0xd, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/k14s/kapp@/pkg/kapp/clusterapply/converged_resource.go:42 +0xeb
github.com/k14s/kapp/pkg/kapp/clusterapply.NewValueResourceConverged(0x0, 0x0, 0x0, 0x8, 0x9, 0xc0000fee00)
        github.com/k14s/kapp@/pkg/kapp/clusterapply/changes_view.go:272 +0x8e
github.com/k14s/kapp/pkg/kapp/clusterapply.(*ChangesView).Print(0xc00038de30, 0x15ad2e0, 0xc00035cec0)
        github.com/k14s/kapp@/pkg/kapp/clusterapply/changes_view.go:119 +0x1254
github.com/k14s/kapp/pkg/kapp/clusterapply.(*ChangeSetView).Print(0xc000856a08, 0x15ad2e0, 0xc00035cec0)
        github.com/k14s/kapp@/pkg/kapp/clusterapply/change_set_view.go:44 +0x3d5
github.com/k14s/kapp/pkg/kapp/cmd/app.(*DeployOptions).calculateAndPresentChanges(0xc0005b0000, 0x0, 0x0, 0x0, 0xc000b8cf80, 0x1, 0x1, 0xc0008ac360, 0x1, 0x1, ...)
        github.com/k14s/kapp@/pkg/kapp/cmd/app/deploy.go:357 +0xc7e
github.com/k14s/kapp/pkg/kapp/cmd/app.(*DeployOptions).Run(0xc0005b0000, 0x0, 0x0)
        github.com/k14s/kapp@/pkg/kapp/cmd/app/deploy.go:143 +0x7cd
github.com/k14s/kapp/pkg/kapp/cmd/app.NewDeployCmd.func1(0xc0005b0280, 0xc000610740, 0x0, 0x4, 0xc000611a00, 0xc000023bc8)
        github.com/k14s/kapp@/pkg/kapp/cmd/app/deploy.go:54 +0x2a
github.com/k14s/kapp/pkg/kapp/cmd.NewKappCmd.func1.1(0xc0005b0280, 0xc000610740, 0x0, 0x4, 0x0, 0x0)
        github.com/k14s/kapp@/pkg/kapp/cmd/kapp.go:127 +0xcc
github.com/cppforlife/cobrautil.ReconfigureLeafCmd.func1(0xc0005b0280, 0xc000610740, 0x0, 0x4, 0x0, 0x0)
        github.com/cppforlife/cobrautil@v0.0.0-20200108171912-b289811fd2b9/misc.go:67 +0x135
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc0005b0280, 0xc000610740, 0x0, 0x4, 0x0, 0x0)
        github.com/cppforlife/cobrautil@v0.0.0-20200108171912-b289811fd2b9/misc.go:25 +0xaf
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc0005b0280, 0xc000610740, 0x0, 0x4, 0x0, 0x0)
        github.com/cppforlife/cobrautil@v0.0.0-20200108171912-b289811fd2b9/misc.go:25 +0xaf
github.com/spf13/cobra.(*Command).execute(0xc0005b0280, 0xc0006106c0, 0x4, 0x4, 0xc0005b0280, 0xc0006106c0)
        github.com/spf13/cobra@v0.0.3/command.go:762 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000eec80, 0xc0000eec80, 0xc00035cec0, 0x10bc432)
        github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
        github.com/k14s/kapp@/cmd/kapp/kapp.go:31 +0x175
```

**Comment by cppforlife** [comment]
@benmoss im curious, separately from the panic, what were you expecting to happen by including metadata.uid (or did you pass it because you did kubectl get and piped it into kapp) compared to without uid?

**Comment by benmoss** [comment]
Yep, I was trying to copy a secret from one namespace to another. I was following [this StackOverflow](https://stackoverflow.com/a/52326812) which tells you to do 

```
kubectl get secret foo -o yaml | k apply --namespace bar -f-
```

now that the `--export` flag has been removed from kubectl. This works with kubectl, but makes kapp blow up.

**Comment by cppforlife** [comment]
fixed in https://github.com/k14s/kapp/commit/c5162f22147632375581992d39598086b05cb417
