### ISSUE TITLE
nil pointer exception

### ISSUE THREAD

**Issue by jstrachan** [k14s/kapp#172]
**What steps did you take:**
I tried running `kapp` on a repository I had (a tree of namespaces/resources)

```bash
	kapp deploy --yes -a label:gitops.jenkins-x.io/pipeline=customresourcedefinitions  -f config-root/customresourcedefinitions
	kapp deploy --yes -a label:gitops.jenkins-x.io/pipeline=cluster                    -f config-root/cluster
	kapp deploy --yes -a label:gitops.jenkins-x.io/pipeline=namespaces                 -f config-root/namespaces
```

It seemed to work better if I used a single top level dir but was trying to reuse the existing labels we'd been using on the Jenkins X project

**What happened:**
I got the following nil pointer:
```
Changes

Namespace  Name                                  Kind                      Conds.  Age  Op      Op st.  Wait to    Rs  Ri
(cluster)  clustertasks.tekton.dev               CustomResourceDefinition  2/2 t   5d   update  -       reconcile  ok  -
^          conditions.tekton.dev                 CustomResourceDefinition  2/2 t   5d   update  -       reconcile  ok  -
^          environments.jenkins.io               CustomResourceDefinition  2/2 t   5d   update  -       reconcile  ok  -
^          externalsecrets.kubernetes-client.io  CustomResourceDefinition  3/3 t   5d   update  -       reconcile  ok  -
^          images.caching.internal.knative.dev   CustomResourceDefinition  2/2 t   5d   update  -       reconcile  ok  -
^          lighthousejobs.lighthouse.jenkins.io  CustomResourceDefinition  2/2 t   5d   update  -       reconcile  ok  -
^          pipelineactivities.jenkins.io         CustomResourceDefinition  2/2 t   5d   update  -       reconcile  ok  -
^          pipelineresources.tekton.dev          CustomResourceDefinition  2/2 t   5d   update  -       reconcile  ok  -
^          pipelineruns.tekton.dev               CustomResourceDefinition  2/2 t   5d   update  -       reconcile  ok  -
^          pipelines.tekton.dev                  CustomResourceDefinition  2/2 t   5d   update  -       reconcile  ok  -
^          previews.preview.jenkins.io           CustomResourceDefinition  2/2 t   5d   update  -       reconcile  ok  -
^          releases.jenkins.io                   CustomResourceDefinition  2/2 t   5d   update  -       reconcile  ok  -
^          runs.tekton.dev                       CustomResourceDefinition  2/2 t   5d   update  -       reconcile  ok  -
^          sourcerepositories.jenkins.io         CustomResourceDefinition  2/2 t   5d   update  -       reconcile  ok  -
^          taskruns.tekton.dev                   CustomResourceDefinition  2/2 t   5d   update  -       reconcile  ok  -
^          tasks.tekton.dev                      CustomResourceDefinition  2/2 t   5d   update  -       reconcile  ok  -

Op:      0 create, 0 delete, 16 update, 0 noop
Wait to: 16 reconcile, 0 delete, 0 noop

9:42:50AM: ---- applying 16 changes [0/16 done] ----
9:42:52AM: update customresourcedefinition/conditions.tekton.dev (apiextensions.k8s.io/v1) cluster
9:42:53AM: update customresourcedefinition/releases.jenkins.io (apiextensions.k8s.io/v1beta1) cluster
9:42:55AM: update customresourcedefinition/pipelineactivities.jenkins.io (apiextensions.k8s.io/v1beta1) cluster
9:42:56AM: update customresourcedefinition/tasks.tekton.dev (apiextensions.k8s.io/v1) cluster
9:42:56AM: update customresourcedefinition/pipelineruns.tekton.dev (apiextensions.k8s.io/v1) cluster
9:42:56AM: update customresourcedefinition/images.caching.internal.knative.dev (apiextensions.k8s.io/v1beta1) cluster
9:42:56AM: update customresourcedefinition/environments.jenkins.io (apiextensions.k8s.io/v1beta1) cluster
9:42:56AM: update customresourcedefinition/lighthousejobs.lighthouse.jenkins.io (apiextensions.k8s.io/v1beta1) cluster
9:42:57AM: update customresourcedefinition/previews.preview.jenkins.io (apiextensions.k8s.io/v1) cluster
9:42:57AM: update customresourcedefinition/sourcerepositories.jenkins.io (apiextensions.k8s.io/v1beta1) cluster
9:42:57AM: update customresourcedefinition/externalsecrets.kubernetes-client.io (apiextensions.k8s.io/v1beta1) cluster
9:42:57AM: update customresourcedefinition/pipelineresources.tekton.dev (apiextensions.k8s.io/v1) cluster
9:42:57AM: update customresourcedefinition/runs.tekton.dev (apiextensions.k8s.io/v1) cluster
9:42:58AM: update customresourcedefinition/clustertasks.tekton.dev (apiextensions.k8s.io/v1) cluster
9:42:58AM: update customresourcedefinition/taskruns.tekton.dev (apiextensions.k8s.io/v1) cluster
9:42:58AM: update customresourcedefinition/pipelines.tekton.dev (apiextensions.k8s.io/v1) cluster
9:42:58AM: ---- waiting on 16 changes [0/16 done] ----
9:42:58AM: ok: reconcile customresourcedefinition/pipelines.tekton.dev (apiextensions.k8s.io/v1) cluster
9:42:58AM: ok: reconcile customresourcedefinition/pipelineruns.tekton.dev (apiextensions.k8s.io/v1) cluster
9:42:58AM: ok: reconcile customresourcedefinition/lighthousejobs.lighthouse.jenkins.io (apiextensions.k8s.io/v1beta1) cluster
9:42:58AM: ok: reconcile customresourcedefinition/sourcerepositories.jenkins.io (apiextensions.k8s.io/v1beta1) cluster
9:42:58AM: ok: reconcile customresourcedefinition/externalsecrets.kubernetes-client.io (apiextensions.k8s.io/v1beta1) cluster
9:42:58AM: ok: reconcile customresourcedefinition/runs.tekton.dev (apiextensions.k8s.io/v1) cluster
9:42:58AM: ok: reconcile customresourcedefinition/pipelineresources.tekton.dev (apiextensions.k8s.io/v1) cluster
9:42:59AM: ok: reconcile customresourcedefinition/images.caching.internal.knative.dev (apiextensions.k8s.io/v1beta1) cluster
9:42:59AM: ok: reconcile customresourcedefinition/conditions.tekton.dev (apiextensions.k8s.io/v1) cluster
9:42:59AM: ok: reconcile customresourcedefinition/releases.jenkins.io (apiextensions.k8s.io/v1beta1) cluster
9:42:59AM: ok: reconcile customresourcedefinition/clustertasks.tekton.dev (apiextensions.k8s.io/v1) cluster
9:42:59AM: ok: reconcile customresourcedefinition/previews.preview.jenkins.io (apiextensions.k8s.io/v1) cluster
9:42:59AM: ok: reconcile customresourcedefinition/pipelineactivities.jenkins.io (apiextensions.k8s.io/v1beta1) cluster
9:42:59AM: ok: reconcile customresourcedefinition/taskruns.tekton.dev (apiextensions.k8s.io/v1) cluster
9:42:59AM: ok: reconcile customresourcedefinition/tasks.tekton.dev (apiextensions.k8s.io/v1) cluster
9:42:59AM: ok: reconcile customresourcedefinition/environments.jenkins.io (apiextensions.k8s.io/v1beta1) cluster
9:42:59AM: ---- applying complete [16/16 done] ----
9:42:59AM: ---- waiting complete [16/16 done] ----

Succeeded
kapp deploy --yes -a label:gitops.jenkins-x.io/pipeline=cluster                    -f config-root/cluster
Target cluster 'https://35.189.116.232' (nodes: gke-jstrachan-tekton-default-pool-5d601ebb-0l2t, 2+)

Changes

Namespace  Name                                        Kind                Conds.  Age  Op      Op st.  Wait to    Rs  Ri
(cluster)  gcactivities-jx                             ClusterRole         -       5d   update  -       reconcile  ok  -
^          gcactivities-jx                             ClusterRoleBinding  -       5d   update  -       reconcile  ok  -
^          ingress-nginx                               ClusterRole         -       53m  update  -       reconcile  ok  -
^          ingress-nginx                               ClusterRoleBinding  -       53m  update  -       reconcile  ok  -
^          ingress-nginx-admission                     ClusterRole         -       53m  update  -       reconcile  ok  -
^          ingress-nginx-admission                     ClusterRoleBinding  -       53m  update  -       reconcile  ok  -
^          jx                                          Namespace           -       5m   update  -       reconcile  ok  -
^          jx-build-controller-jx                      ClusterRole         -       5d   update  -       reconcile  ok  -
^          jx-build-controller-jx                      ClusterRoleBinding  -       5d   update  -       reconcile  ok  -
^          jx-pipelines-visualizer                     ClusterRole         -       5d   update  -       reconcile  ok  -
^          jx-pipelines-visualizer                     ClusterRoleBinding  -       5d   update  -       reconcile  ok  -
^          jx-preview-gc-jobs                          ClusterRole         -       5d   update  -       reconcile  ok  -
^          jx-preview-gc-jobs                          ClusterRoleBinding  -       5d   update  -       reconcile  ok  -
^          jx-production                               Namespace           -       5d   update  -       reconcile  ok  -
^          jx-staging                                  Namespace           -       5d   update  -       reconcile  ok  -
^          kubernetes-external-secrets                 ClusterRole         -       5d   update  -       reconcile  ok  -
^          kubernetes-external-secrets                 ClusterRoleBinding  -       5d   update  -       reconcile  ok  -
^          kubernetes-external-secrets-auth            ClusterRoleBinding  -       5d   update  -       reconcile  ok  -
^          nginx                                       Namespace           -       5d   update  -       reconcile  ok  -
^          nginx-ingress                               ClusterRole         -       5d   update  -       reconcile  ok  -
^          nginx-ingress                               ClusterRoleBinding  -       5d   update  -       reconcile  ok  -
^          pusher-wave-pusher-wave                     ClusterRole         -       5d   update  -       reconcile  ok  -
^          pusher-wave-pusher-wave                     ClusterRoleBinding  -       5d   update  -       reconcile  ok  -
^          secret-infra                                Namespace           -       5d   update  -       reconcile  ok  -
^          tekton-aggregate-edit                       ClusterRole         -       5d   update  -       reconcile  ok  -
^          tekton-aggregate-view                       ClusterRole         -       5d   update  -       reconcile  ok  -
^          tekton-bot                                  ClusterRole         -       5d   update  -       reconcile  ok  -
^          tekton-bot-jx                               ClusterRoleBinding  -       5d   update  -       reconcile  ok  -
^          tekton-pipelines                            Namespace           -       5d   update  -       reconcile  ok  -
^          tekton-pipelines-controller-cluster-access  ClusterRole         -       5d   update  -       reconcile  ok  -
^          tekton-pipelines-controller-cluster-access  ClusterRoleBinding  -       5d   update  -       reconcile  ok  -
^          tekton-pipelines-controller-leaderelection  ClusterRoleBinding  -       5d   update  -       reconcile  ok  -
^          tekton-pipelines-controller-tenant-access   ClusterRole         -       5d   update  -       reconcile  ok  -
^          tekton-pipelines-controller-tenant-access   ClusterRoleBinding  -       5d   update  -       reconcile  ok  -
^          tekton-pipelines-leader-election            ClusterRole         -       5d   update  -       reconcile  ok  -
^          tekton-pipelines-webhook-cluster-access     ClusterRole         -       5d   update  -       reconcile  ok  -
^          tekton-pipelines-webhook-cluster-access     ClusterRoleBinding  -       5d   update  -       reconcile  ok  -
^          tekton-pipelines-webhook-leaderelection     ClusterRoleBinding  -       5d   update  -       reconcile  ok  -

Op:      0 create, 0 delete, 38 update, 0 noop
Wait to: 38 reconcile, 0 delete, 0 noop

9:43:00AM: ---- applying 38 changes [0/38 done] ----
9:43:00AM: update namespace/jx (v1) cluster
9:43:00AM: update namespace/jx-production (v1) cluster
9:43:00AM: update namespace/jx-staging (v1) cluster
9:43:00AM: update clusterrole/ingress-nginx (rbac.authorization.k8s.io/v1) cluster
9:43:00AM: update clusterrolebinding/tekton-pipelines-webhook-leaderelection (rbac.authorization.k8s.io/v1beta1) cluster
9:43:00AM: update namespace/nginx (v1) cluster
9:43:00AM: update namespace/secret-infra (v1) cluster
9:43:00AM: update clusterrole/tekton-aggregate-edit (rbac.authorization.k8s.io/v1) cluster
9:43:00AM: update clusterrolebinding/ingress-nginx (rbac.authorization.k8s.io/v1) cluster
9:43:00AM: update clusterrole/ingress-nginx-admission (rbac.authorization.k8s.io/v1) cluster
9:43:00AM: update clusterrolebinding/ingress-nginx-admission (rbac.authorization.k8s.io/v1) cluster
9:43:00AM: update clusterrole/nginx-ingress (rbac.authorization.k8s.io/v1) cluster
9:43:00AM: update clusterrolebinding/nginx-ingress (rbac.authorization.k8s.io/v1) cluster
9:43:00AM: update clusterrolebinding/kubernetes-external-secrets-auth (rbac.authorization.k8s.io/v1beta1) cluster
9:43:00AM: update clusterrole/kubernetes-external-secrets (rbac.authorization.k8s.io/v1beta1) cluster
9:43:00AM: update clusterrolebinding/kubernetes-external-secrets (rbac.authorization.k8s.io/v1beta1) cluster
9:43:00AM: update clusterrole/pusher-wave-pusher-wave (rbac.authorization.k8s.io/v1) cluster
9:43:00AM: update clusterrolebinding/pusher-wave-pusher-wave (rbac.authorization.k8s.io/v1) cluster
9:43:00AM: update clusterrole/tekton-pipelines-controller-tenant-access (rbac.authorization.k8s.io/v1) cluster
9:43:00AM: update clusterrole/tekton-aggregate-view (rbac.authorization.k8s.io/v1) cluster
9:43:00AM: update clusterrole/tekton-pipelines-controller-cluster-access (rbac.authorization.k8s.io/v1) cluster
9:43:00AM: update clusterrolebinding/tekton-pipelines-controller-cluster-access (rbac.authorization.k8s.io/v1beta1) cluster
9:43:00AM: update clusterrolebinding/tekton-pipelines-controller-leaderelection (rbac.authorization.k8s.io/v1beta1) cluster
9:43:01AM: update clusterrole/jx-preview-gc-jobs (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: update clusterrole/jx-build-controller-jx (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: update clusterrolebinding/jx-build-controller-jx (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: update clusterrole/jx-pipelines-visualizer (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: update clusterrolebinding/jx-pipelines-visualizer (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: update clusterrolebinding/gcactivities-jx (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: update clusterrole/gcactivities-jx (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: update clusterrole/tekton-bot (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: update namespace/tekton-pipelines (v1) cluster
9:43:01AM: update clusterrolebinding/tekton-bot-jx (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: update clusterrolebinding/tekton-pipelines-controller-tenant-access (rbac.authorization.k8s.io/v1beta1) cluster
9:43:01AM: update clusterrole/tekton-pipelines-leader-election (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: update clusterrole/tekton-pipelines-webhook-cluster-access (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: update clusterrolebinding/tekton-pipelines-webhook-cluster-access (rbac.authorization.k8s.io/v1beta1) cluster
9:43:01AM: update clusterrolebinding/jx-preview-gc-jobs (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ---- waiting on 38 changes [0/38 done] ----
9:43:01AM: ok: reconcile clusterrolebinding/tekton-pipelines-webhook-leaderelection (rbac.authorization.k8s.io/v1beta1) cluster
9:43:01AM: ok: reconcile clusterrolebinding/jx-preview-gc-jobs (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrole/tekton-bot (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrole/jx-preview-gc-jobs (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrole/ingress-nginx-admission (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrole/jx-pipelines-visualizer (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrole/jx-build-controller-jx (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrolebinding/jx-build-controller-jx (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrolebinding/tekton-pipelines-controller-tenant-access (rbac.authorization.k8s.io/v1beta1) cluster
9:43:01AM: ok: reconcile namespace/tekton-pipelines (v1) cluster
9:43:01AM: ok: reconcile clusterrolebinding/tekton-bot-jx (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile namespace/jx-production (v1) cluster
9:43:01AM: ok: reconcile namespace/jx (v1) cluster
9:43:01AM: ok: reconcile namespace/jx-staging (v1) cluster
9:43:01AM: ok: reconcile clusterrole/ingress-nginx (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrolebinding/gcactivities-jx (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrolebinding/jx-pipelines-visualizer (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrole/tekton-pipelines-leader-election (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrole/tekton-pipelines-webhook-cluster-access (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile namespace/secret-infra (v1) cluster
9:43:01AM: ok: reconcile namespace/nginx (v1) cluster
9:43:01AM: ok: reconcile clusterrolebinding/tekton-pipelines-webhook-cluster-access (rbac.authorization.k8s.io/v1beta1) cluster
9:43:01AM: ok: reconcile clusterrole/tekton-aggregate-edit (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrolebinding/ingress-nginx (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrole/pusher-wave-pusher-wave (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrolebinding/ingress-nginx-admission (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrolebinding/nginx-ingress (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrolebinding/kubernetes-external-secrets-auth (rbac.authorization.k8s.io/v1beta1) cluster
9:43:01AM: ok: reconcile clusterrole/nginx-ingress (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrole/kubernetes-external-secrets (rbac.authorization.k8s.io/v1beta1) cluster
9:43:01AM: ok: reconcile clusterrolebinding/kubernetes-external-secrets (rbac.authorization.k8s.io/v1beta1) cluster
9:43:01AM: ok: reconcile clusterrolebinding/pusher-wave-pusher-wave (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrole/tekton-aggregate-view (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrolebinding/tekton-pipelines-controller-cluster-access (rbac.authorization.k8s.io/v1beta1) cluster
9:43:01AM: ok: reconcile clusterrole/tekton-pipelines-controller-tenant-access (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrolebinding/tekton-pipelines-controller-leaderelection (rbac.authorization.k8s.io/v1beta1) cluster
9:43:01AM: ok: reconcile clusterrole/tekton-pipelines-controller-cluster-access (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ok: reconcile clusterrole/gcactivities-jx (rbac.authorization.k8s.io/v1) cluster
9:43:01AM: ---- applying complete [38/38 done] ----
9:43:01AM: ---- waiting complete [38/38 done] ----

Succeeded
kapp deploy --yes -a label:gitops.jenkins-x.io/pipeline=namespaces                 -f config-root/namespaces
Target cluster 'https://35.189.116.232' (nodes: gke-jstrachan-tekton-default-pool-5d601ebb-0l2t, 2+)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1bd8586]

goroutine 1 [running]:
github.com/k14s/kapp/pkg/kapp/resources.APIVersionKindMatcher.Matches(0xc000a73ae8, 0x19, 0x1f79b4c, 0x3, 0x0, 0x0, 0x8)
	github.com/k14s/kapp@/pkg/kapp/resources/matchers.go:29 +0x26
github.com/k14s/kapp/pkg/kapp/resourcesmisc.NewKappctrlK14sIoV1alpha1App(0x0, 0x0, 0xb)
	github.com/k14s/kapp@/pkg/kapp/resourcesmisc/kappctrl_k14s_io_v1alpha1_app.go:28 +0x94
github.com/k14s/kapp/pkg/kapp/clusterapply.ConvergedResourceFactory.New.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0xed73f0f82, 0x0, 0x21a60e0, 0x7e4, 0xffffffffffffffff)
	github.com/k14s/kapp@/pkg/kapp/clusterapply/converged_resource_factory.go:33 +0x35
github.com/k14s/kapp/pkg/kapp/clusterapply.ConvergedResource.isResourceDoneApplying(0x0, 0x0, 0x0, 0xc000991570, 0xd, 0xd, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/k14s/kapp@/pkg/kapp/clusterapply/converged_resource.go:156 +0xbb
github.com/k14s/kapp/pkg/kapp/clusterapply.ConvergedResource.IsDoneApplying(0x0, 0x0, 0x0, 0xc000991570, 0xd, 0xd, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/k14s/kapp@/pkg/kapp/clusterapply/converged_resource.go:42 +0xeb
github.com/k14s/kapp/pkg/kapp/clusterapply.NewValueResourceConverged(0x0, 0x0, 0x0, 0x8, 0x9, 0xc000759500)
	github.com/k14s/kapp@/pkg/kapp/clusterapply/changes_view.go:272 +0x8e
github.com/k14s/kapp/pkg/kapp/clusterapply.(*ChangesView).Print(0xc000c3e2a0, 0x21b1dc0, 0xc000384180)
	github.com/k14s/kapp@/pkg/kapp/clusterapply/changes_view.go:119 +0x1254
github.com/k14s/kapp/pkg/kapp/clusterapply.(*ChangeSetView).Print(0xc000a74a08, 0x21b1dc0, 0xc000384180)
	github.com/k14s/kapp@/pkg/kapp/clusterapply/change_set_view.go:44 +0x3d5
github.com/k14s/kapp/pkg/kapp/cmd/app.(*DeployOptions).calculateAndPresentChanges(0xc000156f00, 0xc00049f000, 0x40, 0x40, 0xc000387000, 0xa5, 0x100, 0xc0007c7680, 0x1, 0x1, ...)
	github.com/k14s/kapp@/pkg/kapp/cmd/app/deploy.go:357 +0xc7e
github.com/k14s/kapp/pkg/kapp/cmd/app.(*DeployOptions).Run(0xc000156f00, 0x0, 0x0)
	github.com/k14s/kapp@/pkg/kapp/cmd/app/deploy.go:143 +0x7cd
github.com/k14s/kapp/pkg/kapp/cmd/app.NewDeployCmd.func1(0xc000157180, 0xc00050a230, 0x0, 0x5, 0xc0004adac0, 0xc000101bc8)
	github.com/k14s/kapp@/pkg/kapp/cmd/app/deploy.go:54 +0x2a
github.com/k14s/kapp/pkg/kapp/cmd.NewKappCmd.func1.1(0xc000157180, 0xc00050a230, 0x0, 0x5, 0x0, 0x0)
	github.com/k14s/kapp@/pkg/kapp/cmd/kapp.go:127 +0xcc
github.com/cppforlife/cobrautil.ReconfigureLeafCmd.func1(0xc000157180, 0xc00050a230, 0x0, 0x5, 0x0, 0x0)
	github.com/cppforlife/cobrautil@v0.0.0-20200108171912-b289811fd2b9/misc.go:67 +0x135
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc000157180, 0xc00050a230, 0x0, 0x5, 0x0, 0x0)
	github.com/cppforlife/cobrautil@v0.0.0-20200108171912-b289811fd2b9/misc.go:25 +0xaf
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc000157180, 0xc00050a230, 0x0, 0x5, 0x0, 0x0)
	github.com/cppforlife/cobrautil@v0.0.0-20200108171912-b289811fd2b9/misc.go:25 +0xaf
github.com/spf13/cobra.(*Command).execute(0xc000157180, 0xc00050a1e0, 0x5, 0x5, 0xc000157180, 0xc00050a1e0)
	github.com/spf13/cobra@v0.0.3/command.go:762 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000102c80, 0xc000102c80, 0xc000384180, 0x1cbf7f2)
	github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
```

**What did you expect:**
to not fail ;)

**Comment by danielhelfand** [comment]
Thanks for opening this @jstrachan and sorry for your issues with `kapp`. Would you by chance be able to share the contents of your `config-root` directory to help reproduce this?

**Comment by cppforlife** [comment]
this was fixed on develop btw: https://github.com/vmware-tanzu/carvel-kapp/commit/c5162f22147632375581992d39598086b05cb417. havent made it into a release yet.

**Comment by jstrachan** [comment]
I was just gonna say - I tried out a local build of kapp and it worked perfectly :) so we just need a new release. Sorry for the noise

**Comment by jstrachan** [comment]
any idea when the next kapp release is gonna be? for a while it looked almost monthly cadence but seems to to have stalled in October

**Comment by cppforlife** [comment]
@jstrachan we'll try to publish a version today. releases are mostly need based or when we have good chunk of new features.

**Comment by cppforlife** [comment]
fix is included in https://github.com/vmware-tanzu/carvel-kapp/releases/tag/v0.35.0
