### ISSUE TITLE
kapp service-account null pointer exception

### ISSUE THREAD

**Issue by jessechahal** [k14s/kapp#56]
When first install kapp for the very first time and running against docker-for-mac get the following error

```
 kapp service-account
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1bcdc87]

goroutine 1 [running]:
github.com/k14s/kapp/pkg/kapp/cmd.NewKappCmd.func1.1(0xc000429400, 0x2991748, 0x0, 0x0, 0x0, 0x0)
	/Users/pivotal/workspace/ytt-go/src/github.com/k14s/kapp/pkg/kapp/cmd/kapp.go:120 +0xc7
github.com/k14s/kapp/vendor/github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc000429400, 0x2991748, 0x0, 0x0, 0x0, 0x0)
	/Users/pivotal/workspace/ytt-go/src/github.com/k14s/kapp/vendor/github.com/cppforlife/cobrautil/misc.go:25 +0xaf
github.com/k14s/kapp/vendor/github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc000429400, 0x2991748, 0x0, 0x0, 0x0, 0x0)
	/Users/pivotal/workspace/ytt-go/src/github.com/k14s/kapp/vendor/github.com/cppforlife/cobrautil/misc.go:25 +0xaf
github.com/k14s/kapp/vendor/github.com/spf13/cobra.(*Command).execute(0xc000429400, 0x2991748, 0x0, 0x0, 0xc000429400, 0x2991748)
	/Users/pivotal/workspace/ytt-go/src/github.com/k14s/kapp/vendor/github.com/spf13/cobra/command.go:762 +0x460
github.com/k14s/kapp/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0003fc500, 0xc0003fc500, 0xc000336e40, 0x2917b20)
	/Users/pivotal/workspace/ytt-go/src/github.com/k14s/kapp/vendor/github.com/spf13/cobra/command.go:852 +0x2ea
github.com/k14s/kapp/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/pivotal/workspace/ytt-go/src/github.com/k14s/kapp/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/Users/pivotal/workspace/ytt-go/src/github.com/k14s/kapp/cmd/kapp/kapp.go:26 +0x16f
```

i haven't created any service accounts so assume its a simple null pointer error

**Comment by cppforlife** [comment]
fixed in https://github.com/k14s/kapp/commit/0c3833d868063d229a47e03d6a0ba0932a6f6a8a. help message was superseded by running noop command. will be included in upcoming release. meanwhile you can use `kapp service-account -h`.

**Comment by cppforlife** [comment]
fixed in https://github.com/k14s/kapp/releases/tag/v0.16.0
